// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwh4lBQ_ebS8rbByRcFpIh53es4KOPDwg',
    appId: '1:59409246132:web:65aa62b00185a2dc08f4e1',
    messagingSenderId: '59409246132',
    projectId: 'waqas-developer',
    authDomain: 'waqas-developer.firebaseapp.com',
    storageBucket: 'waqas-developer.firebasestorage.app',
    measurementId: 'G-5QLNDRQX48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkgUsPPfQp72MKbbygIDSHOco0XojO_I',
    appId: '1:59409246132:android:ffdffb1a01ae146208f4e1',
    messagingSenderId: '59409246132',
    projectId: 'waqas-developer',
    storageBucket: 'waqas-developer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJ7BiKYKns4tWhw6V4up7LLqUrkq1-sQ',
    appId: '1:59409246132:ios:a2f2b171ce1f4cb408f4e1',
    messagingSenderId: '59409246132',
    projectId: 'waqas-developer',
    storageBucket: 'waqas-developer.firebasestorage.app',
    iosBundleId: 'com.example.webPotfolio',
  );
}
